CREATE TABLE IF NOT EXISTS roles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(255),
  role VARCHAR(50) NOT NULL,
  company_id BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(255),
  updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS companies (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  industry VARCHAR(100),
  tech_stack TEXT,
  supply_chain_info TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(255),
  updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS risk_categories (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100),
  icon VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS risks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  company_id BIGINT,
  category_id BIGINT,
  title VARCHAR(500) NOT NULL,
  description TEXT,
  severity ENUM('LOW','MEDIUM','HIGH','CRITICAL') DEFAULT 'MEDIUM',
  status ENUM('OPEN','ACKNOWLEDGED','RESOLVED') DEFAULT 'OPEN',
  ai_confidence DECIMAL(5,2),
  detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP NULL,
  source VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(255),
  updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS skills (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  category VARCHAR(100),
  is_emerging BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS employee_skills (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT,
  skill_id BIGINT,
  proficiency ENUM('BEGINNER','INTERMEDIATE','ADVANCED','EXPERT'),
  assessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_user_skill (user_id, skill_id)
);

CREATE TABLE IF NOT EXISTS roadmaps (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT,
  title VARCHAR(500),
  generated_by_ai BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(255),
  updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS roadmap_steps (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  roadmap_id BIGINT,
  skill_id BIGINT,
  step_order INT,
  description TEXT,
  resource_url VARCHAR(500),
  estimated_hours INT,
  completed BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT,
  type VARCHAR(100),
  message TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(255),
  updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ai_cache (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  prompt_hash VARCHAR(64) UNIQUE,
  response_json TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP
);
