spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sovai_db}
    username: ${DB_USER:luffy}
    password: ${DB_PASS:Plmoknijb@123}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
  threads:
    virtual:
      enabled: true

ai:
  api:
    base-url: ${AI_API_URL:https://api.groq.com/openai/v1}
    api-key: ${AI_API_KEY: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}
    model: ${AI_MODEL:llama-3.3-70b-versatile}
    timeout-seconds: 30

jwt:
  secret: ${JWT_SECRET:7jYMds1ou61kcD3dqXXP0bbeKatGGv8Hn3pkFd25Y1NeqXEy/qk9ejjman4u0igWhj4epNo6G58r6RBbNjtwCA==}
  expiration-ms: 86400000

quartz:
  risk-scan-cron: "0 0 */6 * * ?"
  skills-analysis-cron: "0 0 9 ? * MON"

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

